//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Garment = new HashSet<Garment>();
            this.Garment1 = new HashSet<Garment>();
            this.Garment2 = new HashSet<Garment>();
            this.Garment3 = new HashSet<Garment>();
            this.Garment4 = new HashSet<Garment>();
        }
    
        public int ArticleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ColourId { get; set; }
        public string Composition { get; set; }
        public Nullable<decimal> AmountInBatches { get; set; }
        public Nullable<decimal> AmountPerBatch { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<int> AddedByEmployeeId { get; set; }
        public Nullable<int> UpdatedByEmployeeId { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Colour Colour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garment> Garment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garment> Garment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garment> Garment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garment> Garment3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garment> Garment4 { get; set; }
    }
}
