//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garment()
        {
            this.SalesItem = new HashSet<SalesItem>();
        }
    
        public int GarmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Article1Id { get; set; }
        public Nullable<decimal> Article1Amount { get; set; }
        public Nullable<int> Article2Id { get; set; }
        public Nullable<decimal> Article2Amount { get; set; }
        public Nullable<int> Article3Id { get; set; }
        public Nullable<decimal> Article3Amount { get; set; }
        public Nullable<int> Article4Id { get; set; }
        public Nullable<decimal> Article4Amount { get; set; }
        public Nullable<int> Article5Id { get; set; }
        public Nullable<decimal> Article5Amout { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> GarmentTypeId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        public virtual Article Article3 { get; set; }
        public virtual Article Article4 { get; set; }
        public virtual GarmentType GarmentType { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItem> SalesItem { get; set; }
    }
}
