//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public string Number { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> AddedByEmployeeId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> DutyByCountry { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> StatusChangedByEmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
