//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int PaymentId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AddedByEmployeeId { get; set; }
        public Nullable<int> UpdatedByEmployeeId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsIncoming { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Status Status { get; set; }
    }
}
