//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItem
    {
        public int SalesItemId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> GarmentId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    
        public virtual Garment Garment { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
